include(vars.pri)

isEmpty(PREFIX): PREFIX=/usr
QT += core gui widgets
CONFIG += c++11
DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000
DEFINES += BUILD_HOLLYWOOD

INCLUDEPATH += $${PWD}
CONFIG(debug): DESTDIR=$${OBJECTS_DIR}../output/

