/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i dbusmenu_interface.h -p :dbusmenu_interface.cpp ../menuserver/com.canonical.dbusmenu.xml
 *
 * qdbusxml2cpp is Copyright (C) 2022 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusmenu_interface.h"
/*
 * Implementation of interface class ComCanonicalDbusmenuInterface
 */

DBusMenuInterface::DBusMenuInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DBusMenuInterface::~DBusMenuInterface()
{
}

