#ifndef LAYERSHELLQT_EXPORT_H
#define LAYERSHELLQT_EXPORT_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(LAYERSHELLQT)

#if defined(LIBSHELL_LIBRARY)
#  define LAYERSHELLQT_EXPORT Q_DECL_EXPORT
#else
#  define LAYERSHELLQT_EXPORT Q_DECL_IMPORT
#endif

#endif // LAYERSHELLQT_EXPORT_H
