.Dd May 16, 2020
.Dt HORIZON-QT5 1
.Os "Adélie Linux"
.Sh NAME
.Nm horizon-qt5
.Nd create a HorizonScript using a simple user interface
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility allows you to create a HorizonScript using a graphical user interface.
.Sh SEE ALSO
.Xr hscript-validate 1 ,
.Xr hscript 5 ,
.Xr hscript-executor 8 ,
.Xr horizon-run-qt5 8 .
.Sh HISTORY
The
.Nm
utility first appeared in Horizon 0.9.
.Sh AUTHORS
.An A. Wilcox
.Aq awilfox@adelielinux.org
