.Dd May 16, 2020
.Dt HORIZON-PPC64-DETECT 1
.Os "Adélie Linux"
.Sh NAME
.Nm horizon-ppc64-detect
.Nd detect platform characteristics
.Sh SYNOPSIS
.Nm
.Sh DESCRIPTION
The
.Nm
utility determines the platform characteristics of a 64-bit PowerPC computer
for the Horizon installation system.
.Sh FILES
.Bl -tag -width Ds
.It Pa /tmp/horizon-platform
The
.Nm
utility writes the type of platform to
.Pa /tmp/horizon-platform .
.Sh HISTORY
The
.Nm
command first appeared in Horizon 0.9.
.Sh AUTHORS
.An A. Wilcox
.Aq awilfox@adelielinux.org
