project = 'Hollywood Help'
copyright = '2023, Originull Software'
author = 'Originull Software'
release = 'Edge'
extensions = []
templates_path = ['_templates']
exclude_patterns = []
qthelp_namespace = 'org.originull.hollywood.edge'
qthelp_basename = 'org.originull.hollywood'
qthelp_theme = 'nonav'
html_theme = 'pyramid'
html_static_path = ['_static']
html_title = 'Hollywood Users Guide'
